---
language: node_js
node_js:
  - "6"

cache:
  yarn: true

env:
  global:
    - CC_TEST_REPORTER_ID=68bca34aea101c23f266a7a8c38cea0891f1fc517618d28f7329992afd6a44d8

install:
  - npm ci 
  - ./node_modules/lerna/bin/lerna.js bootstrap --hoist --ci

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - ./node_modules/lerna/bin/lerna.js run lint
  - ./node_modules/jest/bin/jest.js --no-cache --coverage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
